import { BurgerType } from "../types/burger-types";

export const selectedIngredients:BurgerType[] = [
   {
     "_id": "60d3b41abdacab0026a733c6",
     "name": "Краторная булка N-200i",
     "type": "bun",
     "proteins": 80,
     "fat": 24,
     "carbohydrates": 53,
     "calories": 420,
     "price": 1255,
     "image": "https://code.s3.yandex.net/react/code/bun-02.png",
     "image_mobile": "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
     "image_large": "https://code.s3.yandex.net/react/code/bun-02-large.png",
     "__v": 0
   },
   {
     "_id": "60d3b41abdacab0026a733c8",
     "name": "Филе Люминесцентного тетраодонтимформа",
     "type": "main",
     "proteins": 44,
     "fat": 26,
     "carbohydrates": 85,
     "calories": 643,
     "price": 988,
     "image": "https://code.s3.yandex.net/react/code/meat-03.png",
     "image_mobile": "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
     "image_large": "https://code.s3.yandex.net/react/code/meat-03-large.png",
     "__v": 0
   },
   {
     "_id": "60d3b41abdacab0026a733cc",
     "name": "Соус Spicy-X",
     "type": "sauce",
     "proteins": 30,
     "fat": 20,
     "carbohydrates": 40,
     "calories": 30,
     "price": 90,
     "image": "https://code.s3.yandex.net/react/code/sauce-02.png",
     "image_mobile": "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
     "image_large": "https://code.s3.yandex.net/react/code/sauce-02-large.png",
     "__v": 0
   },
   {
     "_id": "60d3b41abdacab0026a733ce",
     "name": "Соус традиционный галактический",
     "type": "sauce",
     "proteins": 42,
     "fat": 24,
     "carbohydrates": 42,
     "calories": 99,
     "price": 15,
     "image": "https://code.s3.yandex.net/react/code/sauce-03.png",
     "image_mobile": "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
     "image_large": "https://code.s3.yandex.net/react/code/sauce-03-large.png",
     "__v": 0
   },
   {
     "_id": "60d3b41abdacab0026a733d0",
     "name": "Хрустящие минеральные кольца",
     "type": "main",
     "proteins": 808,
     "fat": 689,
     "carbohydrates": 609,
     "calories": 986,
     "price": 300,
     "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
     "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
     "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
     "__v": 0
   },
   {
    "_id": "60d3b41abdacab0026a733d0",
    "name": "Хрустящие минеральные кольца",
    "type": "main",
    "proteins": 808,
    "fat": 689,
    "carbohydrates": 609,
    "calories": 986,
    "price": 300,
    "image": "https://code.s3.yandex.net/react/code/mineral_rings.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
    "__v": 0
    },
   {
     "_id": "60d3b41abdacab0026a733d2",
     "name": "Кристаллы марсианских альфа-сахаридов",
     "type": "main",
     "proteins": 234,
     "fat": 432,
     "carbohydrates": 111,
     "calories": 189,
     "price": 762,
     "image": "https://code.s3.yandex.net/react/code/core.png",
     "image_mobile": "https://code.s3.yandex.net/react/code/core-mobile.png",
     "image_large": "https://code.s3.yandex.net/react/code/core-large.png",
     "__v": 0
   },
   {
     "_id": "60d3b41abdacab0026a733d3",
     "name": "Мини-салат Экзо-Плантаго",
     "type": "main",
     "proteins": 1,
     "fat": 2,
     "carbohydrates": 3,
     "calories": 6,
     "price": 4400,
     "image": "https://code.s3.yandex.net/react/code/salad.png",
     "image_mobile": "https://code.s3.yandex.net/react/code/salad-mobile.png",
     "image_large": "https://code.s3.yandex.net/react/code/salad-large.png",
     "__v": 0
   },
   {
    "_id": "60d3b41abdacab0026a733d3",
    "name": "Мини-салат Экзо-Плантаго",
    "type": "main",
    "proteins": 1,
    "fat": 2,
    "carbohydrates": 3,
    "calories": 6,
    "price": 4400,
    "image": "https://code.s3.yandex.net/react/code/salad.png",
    "image_mobile": "https://code.s3.yandex.net/react/code/salad-mobile.png",
    "image_large": "https://code.s3.yandex.net/react/code/salad-large.png",
    "__v": 0
  },
   {
     "_id": "60d3b41abdacab0026a733d4",
     "name": "Сыр с астероидной плесенью",
     "type": "main",
     "proteins": 84,
     "fat": 48,
     "carbohydrates": 420,
     "calories": 3377,
     "price": 4142,
     "image": "https://code.s3.yandex.net/react/code/cheese.png",
     "image_mobile": "https://code.s3.yandex.net/react/code/cheese-mobile.png",
     "image_large": "https://code.s3.yandex.net/react/code/cheese-large.png",
     "__v": 0
   }
 ]